### PR TITLE
Edit workout

### PR DESCRIPTION
**Pull request by josephferrairo**
I instantiated user so that it would work when testing current user. I Added Edit Workout and Update Work methods to controller along with tests for successful edit request, user not being logged in and attempts to edit, successful update, unsuccessful update when the user didn't create the workout / isn't logged in,  and user leaving the workout title field blank when attempting to update. I moved the login_user method to the context block in all the previously written tests in the workout spec so that login_user is in the same place through the test suite. I will add the front end of this in another branch or once the bootstrap button branch is completed/merged.

### CODE REVIEW

**Comment by BGRicker** [comment]
where is the link to edit the workout on its show page?

**Comment by josephferrairo** [comment]
Added edit workout link

**Comment by josephferrairo** [comment]
screen shot 2016-10-20 at 4 50 07 pm

**Comment by josephferrairo** [comment]
screen shot 2016-10-20 at 4 52 09 pm
Here is what those buttons look like with the btn-sm tag on them

**Pull request merged**
