### PR TITLE
Blank Workout can't be passed into DB

### PR DESCRIPTION
**Pull request by josephferrairo**
I modified the workout model so that the user cannot input a blank workout, I also modified the workout controller so that it gives the user an error when the user passes a blank workout. I also added tests for new and create workout as well as added a line to the Database cleaner file so that it cleans the db after each test is run.

### CODE REVIEW

**Comment by BGRicker** [comment]
this is weird, but the output string of a blank workout title is

"**Titlecan't** be blank" instead of
"**Title can't** be blank"

I went to add a test for a blank workout and noticed that 🤔

**Comment by BGRicker** [comment]
got it, just doesn't specify "Title" and that was just the last text on the page

**Comment by BGRicker** [comment]
screen shot 2016-10-07 at 9 42 34 pm

**Comment by BGRicker** [comment]
huh I didn't close this

**Comment by josephferrairo** [comment]
wierd

**Pull request closed without merging**
